version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/portfolio/"
    schedule:
      interval: "monthly"
    groups:
      portfolio:
        update-types:
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "typescript"
