version: 2
updates:
  - package-ecosystem: npm
    directory: /portfolio/
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "typescript"
