version: 2
updates:
  - package-ecosystem: npm
    directory: /portfolio/
    schedule:
      interval: monthly
      time: "15:00"
    allow:
      - dependency-name: "*"

    ignore:
      - dependency-name: "typescript"
