version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      ci:
        patterns: ["*"]
    schedule:
      interval: cron
      cronjob: "0 0 1 1,7 *"
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    groups:
      npm:
        patterns: ["*"]
      security:
        applies-to: security-updates
        patterns: ["*"]
    schedule:
      interval: cron
      cronjob: "0 0 1 1,7 *"
    cooldown:
      default-days: 7
