version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        update-types:
          - "major"
          - "minor"
          - "patch"

    ignore:
      - dependency-name: "typescript"
