[serve]
description = "Serve api with hot reloading on changes"
run = "npx vite --open --host"

[clean]
description = "Remove all untracked or safe to remove files"
run = "git clean -fdx"

[lint]
description = "Format all files"
run = ["mise fmt", "npm run check", "npm run compile"]
