name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  deploy:
    needs: lint
    uses: ./.github/workflows/deploy.yaml
