name: Lint & Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Lint & Format
        run: npm run check

      - name: Compile
        run: npm run compile
