name: main

on:
  push:
    branches:
      - main

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yaml

  deploy:
    needs: lint
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yaml
