name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    uses: ./.github/workflows/lint-and-format.yaml

  build-and-deploy:
    needs: lint-and-format
    uses: ./.github/workflows/build-and-deploy.yaml
