name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  