name: Lint & Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Lint & Format

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Check linting and formatting
        run: npm run lint
